name = "trading-review-app"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "trading-review-data"

[vars]
API_TOKEN = "804e422f37109764b26c6a3254443379a85c05f1f445a21fd927af861860ea71"
